server:
    port: 9898
spring:
    application:
        name: authentication-service

    config:
        import: "configserver:http://localhost:8888"

    cloud:
        config:
            discovery:
                enabled: true
                service-id: CONFIG-SERVER
            profile: default
            label: main